#!/bin/bash
# claude-agent Podman 容器启动脚本
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ============================================================
# 可配置变量（可通过 .env 文件覆盖）
# ============================================================
IMAGE_NAME="${CLAUDE_AGENT_IMAGE:-songon/claude-agent}"
CONTAINER_NAME="${CLAUDE_AGENT_NAME:-claude-agent}"

# 挂载路径
CLAUDE_CONFIG_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
SSH_DIR="${SSH_DIR:-$HOME/.ssh}"
REPOSITORY_DIR="${REPOSITORY_DIR:-$HOME/repository}"
CC_HOME_DIR="${CC_HOME_DIR:-$HOME/cc-home}"
DATA_DIR="${DATA_DIR:-$SCRIPT_DIR/data}"

# 资源限制
MEMORY_LIMIT="${MEMORY_LIMIT:-4g}"
CPU_LIMIT="${CPU_LIMIT:-4}"

# HTTP 服务开关(默认关闭)
HTTP_SERVICE_ENABLED="${HTTP_SERVICE_ENABLED:-false}"
HTTP_PORT="${HTTP_PORT:-8765}"
HTTP_API_KEY="${HTTP_API_KEY:-}"

# 代理端口（仅用于构建，0 表示禁用。运行时默认不走代理）
PROXY_PORT="${PROXY_PORT:-7897}"

# 从 settings.json 读取 env 段(让 SDK / cc-connect 在容器内能用同样的 base_url / auth)
CLAUDE_ENV_ARGS=()
if [ -f "$CLAUDE_CONFIG_DIR/settings.json" ] && command -v jq >/dev/null 2>&1; then
    while IFS=$'\t' read -r key value; do
        # 只转发已有值的(防止 ANTHROPIC_API_KEY 为空时覆盖容器内已有值)
        if [ -n "$value" ] && [ "$value" != "PROXY_MANAGED" ]; then
            CLAUDE_ENV_ARGS+=(-e "$key=$value")
        fi
    done < <(jq -r '.env // {} | to_entries[] | [.key, (.value // "" | tostring)] | @tsv' "$CLAUDE_CONFIG_DIR/settings.json" 2>/dev/null)
fi

# 加载 .env 文件（优先级高于默认值）
if [ -f "$SCRIPT_DIR/.env" ]; then
    set -a
    source "$SCRIPT_DIR/.env"
    set +a
fi

# HTTP 服务鉴权:仅在 HTTP_SERVICE_ENABLED=true 时,如果用户没设 HTTP_API_KEY,
# 自动生成一个随机 token 并写入 .env(避免服务在局域网下裸奔)。
# 用户也可在 .env 里手动改成自己想要的;不开服务时完全不读 HTTP_API_KEY,避免误以为启用了鉴权。
if [ "$HTTP_SERVICE_ENABLED" = "true" ] && [ -z "${HTTP_API_KEY:-}" ]; then
    if command -v openssl >/dev/null 2>&1; then
        HTTP_API_KEY=$(openssl rand -hex 24)
    else
        HTTP_API_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(24))' 2>/dev/null || echo "cc-$(date +%s)-$RANDOM")
    fi
    # 持久化到 .env
    ENV_FILE="$SCRIPT_DIR/.env"
    if [ ! -f "$ENV_FILE" ] || ! grep -q "^HTTP_API_KEY=" "$ENV_FILE"; then
        {
            [ -f "$ENV_FILE" ] && echo "" >> "$ENV_FILE"
            echo "# Auto-generated by run.sh on $(date '+%Y-%m-%d %H:%M:%S')" >> "$ENV_FILE"
            echo "HTTP_API_KEY=$HTTP_API_KEY" >> "$ENV_FILE"
        }
        chmod 600 "$ENV_FILE"
        echo ">>> 已自动生成 HTTP_API_KEY 写入 $ENV_FILE(可手动修改)"
    fi
fi

# ============================================================
# 构建 ============================================================
if [[ "${1:-}" == "--build" ]] || ! podman image exists "$IMAGE_NAME" 2>/dev/null; then
    echo ">>> 构建容器镜像..."

    BUILD_ARGS=()
    if [ "$PROXY_PORT" != "0" ]; then
        # 容器内用 host.containers.internal，宿主机检测用 127.0.0.1
        PROXY_URL="http://host.containers.internal:$PROXY_PORT"
        if curl -s --max-time 2 "http://127.0.0.1:$PROXY_PORT" >/dev/null 2>&1; then
            BUILD_ARGS=(
                --build-arg http_proxy="$PROXY_URL"
                --build-arg https_proxy="$PROXY_URL"
                --build-arg HTTP_PROXY="$PROXY_URL"
                --build-arg HTTPS_PROXY="$PROXY_URL"
            )
            echo ">>> 代理 $PROXY_URL 已连接"
        else
            echo ">>> ⚠ 代理 127.0.0.1:$PROXY_PORT 不可达，以无代理模式构建"
        fi
    fi

    podman build --format docker -t "$IMAGE_NAME" -f "$SCRIPT_DIR/Containerfile" "${BUILD_ARGS[@]:-}"
    echo ">>> 清理旧镜像..."
    podman image prune -f 2>/dev/null || true
    echo ">>> 镜像构建完成"
fi

# ============================================================
# 停止旧容器 ============================================================
if podman container exists "$CONTAINER_NAME" 2>/dev/null; then
    echo ">>> 停止旧容器..."
    podman stop -t 30 "$CONTAINER_NAME" 2>/dev/null || true
    podman rm -f "$CONTAINER_NAME" 2>/dev/null || true
fi

# ============================================================
# 启动 ============================================================
echo ">>> 启动 claude-agent 容器..."

mkdir -p "$DATA_DIR" "$CC_HOME_DIR"

# 代理不自动注入容器运行时环境
# 构建时走代理即可，运行时默认不走代理
# 容器内需要时手动执行 px() 开启，用完后 upx() 关闭

# HTTP 服务相关参数(仅在开关启用时追加)
HTTP_RUN_ARGS=()
HTTP_VOLUMES=()
if [ "$HTTP_SERVICE_ENABLED" = "true" ]; then
    HTTP_RUN_ARGS+=(
        -p "${HTTP_PORT}:8765"
        -v "$SCRIPT_DIR/cc-http-uploads:/home/vscode/cc-http-uploads:Z"
        -e HTTP_API_KEY="$HTTP_API_KEY"
        -e HTTP_PORT=8765
        -e HTTP_SERVICE_ENABLED=true
    )
    HTTP_VOLUMES=()
    mkdir -p "$SCRIPT_DIR/cc-http-uploads"
fi

podman run -d \
    --name "$CONTAINER_NAME" \
    --user vscode \
    --restart unless-stopped \
    --stop-timeout 30 \
    --memory "$MEMORY_LIMIT" \
    --cpus "$CPU_LIMIT" \
    --add-host host.containers.internal:host-gateway \
    -v "$DATA_DIR:/home/vscode/.cc-connect:Z" \
    --mount type=tmpfs,destination=/home/vscode/.cc-connect/run,tmpfs-size=16m,tmpfs-mode=1777 \
    -v "$CLAUDE_CONFIG_DIR/settings.json:/home/vscode/.claude/settings.json:Z" \
    -v "$CLAUDE_CONFIG_DIR/CLAUDE.md:/home/vscode/.claude/CLAUDE.md:ro,Z" \
    -v "$SSH_DIR:/home/vscode/.ssh:ro,Z" \
    -v "$REPOSITORY_DIR:/home/vscode/repository:Z" \
    -v "$CC_HOME_DIR:/home/vscode/cc-home:Z" \
    -e ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}" \
    -e OLLAMA_HOST="http://host.containers.internal:11434" \
    -e GIT_TERMINAL_PROMPT=0 \
    ${HTTP_RUN_ARGS[@]+"${HTTP_RUN_ARGS[@]}"} \
    ${CLAUDE_ENV_ARGS[@]+"${CLAUDE_ENV_ARGS[@]}"} \
    "$IMAGE_NAME"

# ============================================================
# 健康检查 ============================================================
echo ">>> 等待 cc-connect 就绪..."
for i in $(seq 1 30); do
  if podman logs "$CONTAINER_NAME" 2>&1 | grep -q "engine started"; then
    echo ">>> ✓ cc-connect 已就绪"
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo ">>> ✗ 启动超时，请查看日志: podman logs $CONTAINER_NAME"
    exit 1
  fi
  sleep 1
done

# 等 HTTP 服务起来(仅在启用时等)
if [ "$HTTP_SERVICE_ENABLED" = "true" ]; then
    echo ">>> 等待 HTTP 服务就绪..."
    HTTP_READY=0
    for i in $(seq 1 30); do
      if curl -s --max-time 2 "http://127.0.0.1:${HTTP_PORT}/health" >/dev/null 2>&1; then
        echo ">>> ✓ HTTP 服务已就绪 (端口 ${HTTP_PORT})"
        HTTP_READY=1
        break
      fi
      sleep 1
    done
    if [ "$HTTP_READY" -eq 0 ]; then
      echo ">>> ⚠ HTTP 服务未就绪，查看日志: podman exec $CONTAINER_NAME cat /tmp/cc-http.log"
    fi

    echo ">>> 调用方法:"
    echo ">>>   健康检查:   curl http://localhost:${HTTP_PORT}/health"
    if [ -n "$HTTP_API_KEY" ]; then
      echo ">>>   带鉴权:    curl -H 'Authorization: Bearer ${HTTP_API_KEY}' http://localhost:${HTTP_PORT}/v1/query -d '{\"prompt\":\"hi\"}' -H 'Content-Type: application/json'"
    fi
    echo ">>>   详细文档:   http://localhost:${HTTP_PORT}/docs"
    echo ">>> HTTP日志:   podman exec $CONTAINER_NAME cat /tmp/cc-http.log"
fi
echo ""
echo ">>> 查看日志:   podman logs -f $CONTAINER_NAME"
echo ">>> 状态:       podman ps --filter name=$CONTAINER_NAME"
echo ">>> 停止:       podman rm -f $CONTAINER_NAME"
